## option firmware

macro(use_peripheral path)
  if(DEFINED "USE_ADC")
    set (FIREWARE_SRC_FILE "stm32f10x_adc.c")
  endif(USE_ADC)
  ## for bkp
  if(DEFINED "USE_BKP")
    set (FIREWARE_SRC_FILE "stm32f10x_bkp.c")
  endif(USE_BKP)
  ## for can
  if(DEFINED "USE_CAN")
    set (FIREWARE_SRC_FILE "stm32f10x_can.c")
  endif(USE_CAN)
  ## for cec
  if(DEFINED "USE_CEC")
    set (FIREWARE_SRC_FILE "stm32f10x_cec.c")
  endif(USE_CEC)
  ## for crc
  if(DEFINED "USE_CRC")
    set (FIREWARE_SRC_FILE "stm32f10x_crc.c")
  endif(USE_CRC)
  ## for dac
  if(DEFINED "USE_DAC")
    set (FIREWARE_SRC_FILE "stm32f10x_dac.c")
  endif(USE_DAC)
  ## for dbgmcu
  if(DEFINED "USE_DBGMCU")
    set (FIREWARE_SRC_FILE "stm32f10x_dbgmcu.c")
  endif(USE_DBGMCU)
  ## for dma
  if(DEFINED "USE_DMA")
    set (FIREWARE_SRC_FILE "stm32f10x_dma.c")
  endif(USE_DMA)
  ## for exti
  if(DEFINED "USE_EXTI")
    set (FIREWARE_SRC_FILE "stm32f10x_exti.c")
  endif(USE_EXTI)
  ## for flash
  if(DEFINED "USE_FLASH")
    set (FIREWARE_SRC_FILE "stm32f10x_flash.c")
  endif(USE_FLASH)
  ## for fsmc
  if(DEFINED "USE_FSMC")
    set (FIREWARE_SRC_FILE "stm32f10x_fsmc.c")
  endif(USE_FSMC)
  ## for gpio
  if(DEFINED "USE_GPIO")
    set (FIREWARE_SRC_FILE "stm32f10x_gpio.c")
  endif(USE_GPIO)
  ## for i2c
  if(DEFINED "USE_I2C")
    set (FIREWARE_SRC_FILE "stm32f10x_i2c.c")
  endif(USE_I2C)
  ## for iwdg
  if(DEFINED "USE_IWDG")
    set (FIREWARE_SRC_FILE "stm32f10x_iwdg.c")
  endif(USE_IWDG)
  ## for pwr
  if(DEFINED "USE_PWR")
    set (FIREWARE_SRC_FILE "stm32f10x_pwr.c")
  endif(USE_PWR)
  ## for rcc
  if(DEFINED "USE_RCC")
    set (FIREWARE_SRC_FILE "stm32f10x_rcc.c")
  endif(USE_RCC)
  ## for rtc
  if(DEFINED "USE_RTC")
    set (FIREWARE_SRC_FILE "stm32f10x_rtc.c")
  endif(USE_RTC)
  ## for sdio
  if(DEFINED "USE_SDIO")
    set (FIREWARE_SRC_FILE "stm32f10x_sdio.c")
  endif(USE_SDIO)
  ## for spi
  if(DEFINED "USE_SPI")
    set (FIREWARE_SRC_FILE "stm32f10x_spi.c")
  endif(USE_SPI)
  ## for tim
  if(DEFINED "USE_TIM")
    set (FIREWARE_SRC_FILE "stm32f10x_tim.c")
  endif(USE_TIM)
  ## for usart
  if(DEFINED "USE_USART")
    set (FIREWARE_SRC_FILE "stm32f10x_usart.c")
  endif(USE_USART)
  ## for wwdg
  if(DEFINED "USE_WWDG")
    set (FIREWARE_SRC_FILE "stm32f10x_wwdg.c")
  endif(USE_WWDG)
  ## config file
  configure_file(
    "${FIRMWARE_PATH}/stm32f10x_conf.h.in"
    "${ARGV0}/stm32f10x_conf.h"
    )
  include_directories("${ARGV0}") 
endmacro(use_peripheral)
macro(ON_ADC)
  set (USE_ADC "#include \"stm32f10x_adc.h\"")
endmacro(USE_ADC)
macro(ON_BKP)
  set (USE_BKP "#include \"stm32f10x_bkp.h\"")
endmacro(USE_BKP)
macro(ON_CAN)
  set (USE_CAN "#include \"stm32f10x_can.h\"")
endmacro(USE_CAN)
macro(ON_CEC)
  set (USE_CEC "#include \"stm32f10x_cec.h\"")
endmacro(USE_CEC)
macro(ON_CRC)
  set (USE_CRC "#include \"stm32f10x_crc.h\"")
endmacro(USE_CRC)
macro(ON_DAC)
  set (USE_DAC "#include \"stm32f10x_dac.h\"")
endmacro(USE_DAC)
macro(ON_DBGMCU)
  set (USE_DBGMCU "#include \"stm32f10x_dbgmcu.h\"")
endmacro(USE_DBGMCU)
macro(ON_DMA)
  set (USE_DMA "#include \"stm32f10x_dma.h\"")
endmacro(USE_DMA)
macro(ON_EXTI)
  set (USE_EXTI "#include \"stm32f10x_exti.h\"")
endmacro(USE_EXTI)
macro(ON_FLASH)
  set (USE_FLASH "#include \"stm32f10x_flash.h\"")
endmacro(USE_FLASH)
macro(ON_FSMC)
  set (USE_FSMC "#include \"stm32f10x_fsmc.h\"")
endmacro(USE_FSMC)
macro(ON_GPIO)
  set (USE_GPIO "#include \"stm32f10x_gpio.h\"")
endmacro(USE_GPIO)
macro(ON_I2C)
  set (USE_I2C "#include \"stm32f10x_i2c.h\"")
endmacro(USE_I2C)
macro(ON_IWDG)
  set (USE_IWDG "#include \"stm32f10x_iwdg.h\"")
endmacro(USE_IWDG)
macro(ON_PWR)
  set (USE_PWR "#include \"stm32f10x_pwr.h\"")
endmacro(USE_PWR)
macro(ON_RCC)
  set (USE_RCC "#include \"stm32f10x_rcc.h\"")
endmacro(USE_RCC)
macro(ON_RTC)
  set (USE_RTC "#include \"stm32f10x_rtc.h\"")
endmacro(USE_RTC)
macro(ON_SDIO)
  set (USE_SDIO "#include \"stm32f10x_sdio.h\"")
endmacro(USE_SDIO)
macro(ON_SPI)
  set (USE_SPI "#include \"stm32f10x_spi.h\"")
endmacro(USE_SPI)
macro(ON_TIM)
  set (USE_TIM "#include \"stm32f10x_tim.h\"")
endmacro(USE_TIM)
macro(ON_USART)
  set (USE_USART "#include \"stm32f10x_usart.h\"")
endmacro(USE_USART)
macro(ON_WWDG)
  set (USE_WWDG "#include \"stm32f10x_wwdg.h\"")
endmacro(USE_WWDG)

